# Generated by Django 2.2.4 on 2019-08-22 15:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False, verbose_name='UUID')),
                ('gmt_create', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('gmt_modified', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('name', models.CharField(max_length=32, verbose_name='区域')),
                ('url', models.CharField(max_length=255, verbose_name='url')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False, verbose_name='UUID')),
                ('gmt_create', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('gmt_modified', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('name', models.CharField(max_length=32, verbose_name='信息')),
                ('code', models.CharField(max_length=32, verbose_name='供获取站点和实时信息使用')),
                ('area', models.ForeignKey(max_length=32, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bus_info.Area', verbose_name='所属区域')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False, verbose_name='UUID')),
                ('gmt_create', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('gmt_modified', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('name', models.CharField(max_length=32, verbose_name='站名')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusInfoStation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False, verbose_name='UUID')),
                ('gmt_create', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('gmt_modified', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businfostation_bus', to='bus_info.BusInfo', verbose_name='bus')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businfostation_station', to='bus_info.Station', verbose_name='station')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
