# Generated by Django 2.2.4 on 2019-08-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businfo',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='信息'),
        ),
    ]
